name: Cloud Testing Pipeline

on:
  push:
  pull_request:

jobs:

  cloud-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Cloud Tests
      run: npm test
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: cloud-test-report
        path: reports/
        retention-days: 7